### ISSUE TITLE
Connection Error with Default Server Installation

### ISSUE THREAD

**Issue by blob5** [oddlama/minecraft-server#13]
I have just installed the server using the automatic installation process. However, when attempting to connect to the server, the proxy console displays the following error:

```
[20:55:25 INFO]: [connected player] USER (/IP:55232) has connected
[20:55:25 INFO] [vane-velocity]: Connection 'USER ' is connecting to 'server'
[20:55:25 INFO] [vane-velocity]: Disconnecting 'USER ' because they don't have the permission to start server 'server'
[20:55:25 INFO]: [connected player] USER (/IP:55232) has disconnected: Server is offline

```
This issue occurs while using the default configurations.
**Steps to Reproduce:**

- Install the server using the automatic installation process.
- Attempt to connect to the server.

**Configuration Details:**

- Configuration File: proxy/plugins/vane-velocity/config.toml
- Setting: allow_anyone is set to true (as per default settings).
- Plugins: No additional plugins have been added.

**Expected Behavior:**

Users should be able to connect to the server without encountering permission-related disconnections when allow_anyone is set to true.

**Actual Behavior:**

Users are disconnected with the message indicating they lack permission to start the server.
**Additional Information:**

No modifications have been made to the default configuration.

**Comment by oddlama** [comment]
I'm sorry for the inconvenience, this is due to the in-progress update to 1.21 of some of the components. We had to switch from waterfall to velocity since waterfall is no longer supported, but the relevant setting to allow server starting is not yet released.

You can work around this by downloading a newer vane-velocity.jar file from [here](https://github.com/oddlama/vane/actions/runs/9891175679/artifacts/1690797655) and overwrite the existing file in the ´proxy/plugins/` folder

**Comment by blob5** [comment]
Thanks for the quick reply!, this fixed it!
